"""add category and additional_topics to users

Revision ID: 29d07e8a4c07
Revises: 1192124a13be
Create Date: 2026-07-23 12:58:51.930317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "29d07e8a4c07"
down_revision: Union[str, Sequence[str], None] = "1192124a13be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("category", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "additional_topics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "additional_topics")
    op.drop_column("users", "category")
    # ### end Alembic commands ###
