"""add user_id to device_tokens

Revision ID: c930ff1670ae
Revises: 4e58efb7c624
Create Date: 2026-08-14 08:30:30.679007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c930ff1670ae'
down_revision: Union[str, Sequence[str], None] = '4e58efb7c624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_tokens', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'device_tokens', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_tokens', type_='foreignkey')
    op.drop_column('device_tokens', 'user_id')
    # ### end Alembic commands ###
